const passport = require('passport');
const GoogleStrategy = require('passport-google-oauth20').Strategy;
const mongoose = require('mongoose');
const keys = require('../config/keys');

const User = mongoose.model('users');

//Turn a MongoDB instance into a user ID
passport.serializeUser((user, done) => {
  // user.id is completely different from the googleId (profile.id), so we consider the ID generated by mongoDB
  done(null, user.id);
});

//Turn an ID into a MongoDB instances
passport.deserializeUser((id, done) => {
  User.findById(id).then((user) => {
    done(null, user);
  });
});

passport.use(
  new GoogleStrategy(
    {
      clientID: keys.googleClientID,
      clientSecret: keys.googleClientSecret,
      callbackURL: '/auth/google/callback',
      // making proxy property true is makes the http become https (no more error)
      proxy: true,
    },
    async (accessToken, refreshToken, profile, done) => {
      const existingUser = await User.findOne({ googleId: profile.id });

      if (existingUser) {
        // we already have a record with the given profile ID
        done(null, existingUser);
      } else {
        // we don't have a user record with this ID, make a new record
        const user = await new User({
          googleId: profile.id,
          email: profile.emails[0].value,
        }).save();
        done(null, user);
      }
    }
  )
);
