const passport = require('passport');
const GoogleStrategy = require('passport-google-oauth20').Strategy;
const mongoose = require('mongoose');
const keys = require('../config/keys');

const User = mongoose.model('users');

//Turn a MongoDB instance into a user ID
passport.serializeUser((user, done) => {
  // user.id is completely different from the googleId (profile.id), so we consider the ID generated by mongoDB
  done(null, user.id);
});

//Turn an ID into a MongoDB instances
passport.deserializeUser((id, done) => {
  User.findById(id).then((user) => {
    done(null, user);
  });
});

passport.use(
  new GoogleStrategy(
    {
      clientID: keys.googleClientID,
      clientSecret: keys.googleClientSecret,
      callbackURL: '/auth/google/callback',
<<<<<<< HEAD
      // making proxy property true is makes the http become https (no more error)
=======
      // making proxy property true is makes the http become https
>>>>>>> 6d80c9bd674aef0d0ee1fb83f24e691ae86a24ec
      proxy: true,
    },
    (accessToken, refreshToken, profile, done) => {
      User.findOne({ googleId: profile.id }).then((existingUser) => {
        if (existingUser) {
          // we already have a record with the given profile ID
          done(null, existingUser);
        } else {
          // we don't have a user record with this ID, make a new record
          new User({ googleId: profile.id, email: profile.emails[0].value })
            .save()
            .then((user) => done(null, user));
        }
      });
    }
  )
);
